name: ClickLimiter
version: 1.1.0
main: com.ratger.clicklimiter.ClickLimiter
api-version: '1.21'
authors: [ ratger ]
description: Limits the maximum CPS
website: https://minetoday.org
depend: [ packetevents ]

commands:
  cl-set:
    description: Set the maximum CPS
    usage: /cl-set <cps>

permissions:
  clicklimiter.set:
    description: Allows using /cl-set
    default: op
  clicklimiter.bypass:
    description: Bypasses the click limiter
    default: false